# Generated by Django 4.0.4 on 2022-05-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alvo',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
